# --- Fuente ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        12.0

# --- Apariencia ---
window_padding_width 10
background_opacity   0.92
confirm_os_window_close 0

# --- Cursor ---
cursor_shape beam
cursor_blink_interval 0.5

# --- Tema Catppuccin Mocha ---
include ./catppuccin-mocha.conf

# --- Shell por defecto ---
shell zsh

# --- Tabs ---
tab_bar_edge bottom
tab_bar_style powerline
